blog/urls.py
from django.urls import path

from blog.views.comment import CommentCreate
from blog.views.home import home
from blog.views.post import PostView, PostCreate, PostUpdate, PostDelete
from blog.views.help_requests import help_requests, RequestView
from blog.views.findmissing import findMissing,results
from blog.views.post_cls import PostClassView 


app_name = 'blog'
urlpatterns = [
    # ex: /blog/
    path('', home, name='home'),
    path('findMissing', findMissing, name='find-missing'),
    path('results', results, name='myresults'),
    # # ex: /blog/dusan
    path('helprequests', help_requests, name='help-requests'),
    path('dclass/<int:pk>', PostClassView.as_view(), name='post_clas'),

    path('requests/<int:pk>', RequestView.as_view(), name='request'),

    # path('',accept_volunteering, name='accept_volunteering')
    # path('',reject_volunteering, name='reject_volunteering')
    # ex: /blog/post/5/
    path('post/<int:pk>/', PostView.as_view(), name='post'),
    # ex: /blog/post/5/comment/
    path('post/<int:pk>/comment/', CommentCreate.as_view(), name='create_comment')
]

mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from blog.views.register import RegisterView

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='blog/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='blog:home')),
    path('register/', RegisterView.as_view(), name='register'),
    path('', include('django.contrib.auth.urls'))
]

blog/models/clasDict.py
classes = {
	1: "Caution/Advice",
	2: "Damage",
	3: "Disease",
	4: "Information",
	5: "Need Help",
	6: "Other",
	7: "People Affected",
	8: "Support",
}

blog/models/image.py
from django.db import models

class Image(models.Model):
    name = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='media/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

blog/models/post.py
from django.db import models
from django.urls import reverse
from blog.models import clasDict

class Post(models.Model):
    body = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    clss = models.IntegerField()
    location = models.TextField()

    def get_absolute_url(self):
        return reverse('blog:post', kwargs={'pk': self.pk})

    def __str__(self):
        return '{body} by {clss}'.format(body=self.body,
                                                clss=clasDict.classes[self.clss])

blog/forms.py
from django import forms
from blog.models.image import Image

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('name', 'document', )

blog/views/comment.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView

from blog.models.comment import Comment
from blog.models.post import Post

CHOICES = [
    (1, "Caution/Advice"),
    (2, "Damage"),
    (3, "Disease"),
    (4, "Information"),
    (5, "Need Help"),
    (6, "Other"),
    (7, "People Affected"),
    (8, "Support")]

class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['vote']
    template_name = 'blog/create_comment.html'
    login_url = reverse_lazy('login')
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in the username
        context['post'] = Post.objects.get(id=self.kwargs['pk'])
        context['choices'] = CHOICES
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post = Post.objects.get(id=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:post', kwargs={'pk': self.kwargs['pk']})

blog/views/findmissing.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from blog.forms import DocumentForm
from django.http import HttpResponse, HttpResponseRedirect
from blog.views.identify_face import searchImage

def findMissing(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            result = searchImage(request.FILES['document'].name, form.cleaned_data['name'])
            request.session['result'] = result
            return HttpResponseRedirect(reverse('blog:myresults'))
    else:
        form = DocumentForm()
    return render(request, 'blog/findMissing.html', {
        'form': form
    })

def results(request):
	return render(request,"blog/results.html",{"result":request.session['result']})

blog/views/help_requests.py
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import render
from blog.models.help_request import Request
from django.template.defaulttags import register
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import CreateView, UpdateView, DeleteView
CHOICES = [(1,"Pending"), (2, "Assigned"), (3, "Resolved")]
choices = {1: "Pending", 2: "Assigned", 3: "Resolved"}
@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)
    
NUM_OF_POSTS = 10


def help_requests(request):
    requests_list = Request.objects.all().order_by('-pub_date')

    paginator = Paginator(requests_list, NUM_OF_POSTS)  # Show NUM_OF_PAGES posts per page
    page = request.GET.get('page')

    requests = paginator.get_page(page)
    return render(request, 'blog/helprequests.html', {'rqsts': requests, 'choices': choices })

def assign(request):
    pass

class RequestView(generic.DetailView):
    model = Request
    template_name = 'blog/request.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in the username
        request = Request.objects.get(id=self.kwargs['pk'])
        context['req'] = request
        context['choices'] = choices
        return context

blog/views/home.py
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import render
from blog.models.clasDict import classes
from blog.models.post import Post
from django.template.defaulttags import register
@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)

    
def home(request, username=None):
    post_list = Post.objects.all().order_by('-pub_date')

    # paginator = Paginator(post_list, NUM_OF_POSTS)  # Show NUM_OF_PAGES posts per page
    # page = request.GET.get('page')

    # posts = paginator.get_page(page)

    return render(request, 'blog/home.html', {'posts': post_list,'classes':classes})

blog/views/identify_face.py
import os
import numpy as np
import face_recognition
import pickle

dir_path = os.path.dirname(os.path.realpath(__file__))

def searchImage(img_path, name):

	with open(dir_path+'/face_recognition_encodings.pkl','rb') as f:
		encodings,tags,images = pickle.load(f)

	new_picture = face_recognition.load_image_file("/home/junaid/Downloads/CodeFunDo/BlogPost/media/media/"+img_path)
	new_face_encoding = face_recognition.face_encodings(new_picture)

	if len(new_face_encoding) < 1:
		return ('No face recognised, please input more clear picture')
	else:
		# print(type(new_face_encoding),new_face_encoding,list(encodings.values())[:5])
		results = face_recognition.compare_faces(list(encodings.values()), new_face_encoding[0])
		if any(results):
			return 'This person is already in our database with name :',list(encodings.keys())[results.index(True)]
		else:
			encodings[name] = new_face_encoding[0]
			
			with open('face_recognition_encodings.pkl','wb') as f:
				pickle.dump([encodings,tags,images],f)

blog/views/post.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import CreateView, UpdateView, DeleteView

from blog.models.comment import Comment
from blog.models.post import Post
from blog.models.clasDict import classes

class PostView(generic.DetailView):
    model = Post
    template_name = 'blog/post.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in the username
        comments = Comment.objects.filter(post=self.kwargs['pk'])
        votes = dict()
        for comment in comments:
            try:
                votes[classes[comment.vote]] += 1
            except:
                votes[classes[comment.vote]]  = 1 

        context['votes'] = votes
        return context


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['body']
    template_name = 'blog/create_post.html'
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.location = "None"
        form.instance.clss = 1
        return super().form_valid(form)


class PostUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'body']
    template_name = 'blog/create_post.html'
    login_url = reverse_lazy('login')

    def test_func(self):
        return Post.objects.get(id=self.kwargs['pk']).user == self.request.user


class PostDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:home')
    login_url = reverse_lazy('login')

    def test_func(self):
        return Post.objects.get(id=self.kwargs['pk']).user == self.request.user

blog/views/post_cls.py
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import render
from blog.models.clasDict import classes
from blog.models.post import Post
from django.template.defaulttags import register
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import CreateView, UpdateView, DeleteView

from blog.models.comment import Comment
from blog.models.post import Post
from blog.models.clasDict import classes

@register.filter

def get_item(dictionary, key):
    return dictionary.get(key)
    
class PostClassView(generic.DetailView):
    model = Post
    template_name = 'blog/post_class.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.filter(clss=self.kwargs['pk'])
        context['classes'] = classes
        return context

blog/views/register.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView


class RegisterView(CreateView):
    model = User
    fields = ['username', 'password', 'first_name', 'last_name', 'email']
    template_name = 'blog/registration.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        # Hash password before sending it to super
        form.instance.password = make_password(form.instance.password)
        return super().form_valid(form)

blog/views/tweet_classifier.py
#!/usr/bin/env python
# coding: utf-8

import pickle,os,sys,re
import numpy as np
import pandas as pd

import pickle, re, csv, string, nltk
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
from gensim.models import Word2Vec
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import normalize

dir_path = os.path.dirname(os.path.realpath(__file__))

def stripPunc(wordList):
    """Strips punctuation from list of words"""
    puncList = [".",";",":","!","?","/","\\",",","$","&",")","(","\""]
    for punc in puncList:
        for word in wordList:
            wordList=[word.replace(punc,'') for word in wordList]
    return wordList

def hash_handler(word):
    if word[0] is not '#':
        return [word]
    word = word[1:]
    return [a for a in re.split('([A-Z][a-z]+)', word) if a]

def categorise(X):
    states,map_states = np.unique(X,return_inverse=True)
#     print states
#     print map_states.shape
    return states,map_states

def classifier(x_train,y_train,x_test,y_test,clf,name,text,mappings):
    clf.fit(x_train,y_train)

    # pred_t = clf.predict(x_train)
    pred = clf.predict(x_test)


    # cf = confusion_matrix(y_test,pred)
    return clf.predict_proba(x_test), accuracy_score(y_test,pred)


def preprocess(tweet):
    urls = []
    m=re.search(r"http\S+", tweet)
    if(m):    
        tweet = str(re.sub(r"http\S+", "", tweet))


    l = stripPunc(tweet.split(" "))
    tweet = ' '.join([x for x in l])

    with open(dir_path+'/OOV_Dict/OOV_Dictionary_V1.0.tsv', 'rt',encoding='latin-1') as f:
        oov = [row for row in csv.reader(f.read().splitlines())]

    out = list()
    rep = list()
    for line in oov:
        w1,w2 = line[0].split('\t')
        out.append(w1)
        rep.append(w2)

    sw = set(stopwords.words('english'))

    out_cnt = 0
    words = list()
    for word in tweet.split():
        word = hash_handler(word)
        for w in word:
            if w not in sw and w[0] is not '@' and w[0] not in string.punctuation:
                if w in out:
                    out_cnt += 1
                    w = rep[out.index(w)]
                words.append(w.lower())
    return words

def main(datafile,labelfile):
    text = []
    with open(dir_path+'/'+datafile) as f:
        for row in f:
            text.append((row.strip()))


    tag = []
    with open(dir_path+'/'+labelfile) as f:
        for row in f:
            tag.append((row.strip()))
    corpus = list()
    # out_cnt = 0
    for tweet in text:
        t = preprocess(tweet)
        # print(t)
        corpus.append(t)


    size=100
    model = Word2Vec(corpus,min_count=1,size=size,window=5,sg=1)

    words = list(model.wv.vocab)

    embed_size = size
    embed_data = list()
    final_labels = list()
    final_text = list()

    for i,tweet in enumerate(corpus):
        temp = np.zeros(embed_size)
        cnt = 0
        for w in tweet:
            temp = np.add(temp,model.wv[w.lower()])
            cnt += 1
        if cnt:
            temp = np.divide(temp,cnt)
            embed_data.append(temp)
            final_labels.append(tag[i])
            final_text.append(text[i])


    # In[21]:


    embed_data = np.asarray(embed_data)
    final_labels = np.asarray(final_labels)
    final_text = np.asarray(final_text)

    mappings,mapped_labels = categorise(final_labels)

    x_train, x_test, y_train, y_test, train_text, test_text = train_test_split(
        embed_data,mapped_labels,final_text,test_size=0.2,random_state=15)
    gbdt = GradientBoostingClassifier(n_estimators=150,verbose=0)
    gbdt_prob, gbdt_acc = classifier(x_train,y_train,x_test,y_test,gbdt,'gbdt',test_text,mappings)

    knn = KNeighborsClassifier(n_neighbors=25)
    knn_prob, knn_acc = classifier(x_train,y_train,x_test,y_test,knn,'knn',test_text,mappings)

    lr = LogisticRegression(verbose=0,max_iter=1)
    lr_prob, lr_acc = classifier(x_train,y_train,x_test,y_test,lr,'lr',test_text,mappings)

    mlp = MLPClassifier(hidden_layer_sizes=(128, 64, 32),verbose=0,random_state=15)
    mlp_prob, mlp_acc = classifier(x_train,y_train,x_test,y_test,mlp,'mlp',test_text,mappings)
    fused_prob = np.add(gbdt_acc*normalize(gbdt_prob),knn_acc*normalize(knn_prob))
    fused_prob = np.add(fused_prob,lr_acc*normalize(lr_prob))
    fused_prob = np.add(fused_prob,mlp_acc*normalize(mlp_prob))

    gbdt = mlp = knn = lr
    gbdt_acc = mlp_acc = knn_acc = lr_acc
    fused_prob = lr_prob
    fused_pred = np.argmax(fused_prob,axis=1)
    mapped_pred = mappings[fused_pred]

    return (gbdt,gbdt_acc,mlp,mlp_acc,lr,lr_acc,knn,knn_acc,model,mappings)
   

blog/views/volunteer.py
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import render
from blog.models.clasDict import classes
from blog.models.post import Post
from blog.models.volunteer import Volunteer
from django.template.defaulttags import register
@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)
    
NUM_OF_POSTS = 5


def accept_volunteering(request):
    post_list = Post.objects.all().order_by('-pub_date')

    paginator = Paginator(post_list, NUM_OF_POSTS)  # Show NUM_OF_PAGES posts per page
    page = request.GET.get('page')

    posts = paginator.get_page(page)

    Volunteer(person=request.session.user).save()

    return render(request, 'blog/home.html', {'posts': posts,'classes':classes,"message": "Thanks for volunteering"})

def reject_volunteering(request):
    post_list = Post.objects.all().order_by('-pub_date')

    paginator = Paginator(post_list, NUM_OF_POSTS)  # Show NUM_OF_PAGES posts per page
    page = request.GET.get('page')

    posts = paginator.get_page(page)

    return render(request, 'blog/home.html', {'posts': posts,'classes':classes})

blog/templates/blog/base.html
<!-- this is base template with navbar and footer -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Disaster Help Predictor</title>
    <link href="http://cdn.jsdelivr.net/webjars/bootstrap/3.3.4/css/bootstrap.min.css"
          rel="stylesheet" media="screen"/>
    <script src="http://cdn.jsdelivr.net/webjars/jquery/2.1.4/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}"/>
</head>
<body>

<!-- navbar -->
<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'blog:home' %}">Disaster Help Predictor</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse navbar-right">
            <!-- show registration only if user is not yet authenticated -->
            {% if not user.is_authenticated %}
                <ul class="nav navbar-nav ">
                    <li class="active"><a href="{% url 'register' %}">Registration</a></li>
                </ul>
            {% endif %}
            <!-- show login only if user is not yet authenticated -->
            {% if not user.is_authenticated %}
                <ul class="nav navbar-nav ">
                    <li class="active"><a href="{% url 'login' %}">Login</a></li>
                </ul>
            {% endif %}
            <!-- show My Blog only if user is authenticated -->
            
            <ul class="nav navbar-nav ">
                <li class="active"><a href="{% url 'blog:help-requests' %}">Requests</a></li>
            </ul>
            <ul class="nav navbar-nav ">
                <li class="active"><a href="{% url 'blog:find-missing' %}">Find Missing Person</a></li>
            </ul>
            <!-- show sign out only if user is authenticated -->
            {% if user.is_authenticated %}
                <ul class="nav navbar-nav ">
                    <li class="active"><a href="{% url 'logout' %}">Sign Out</a></li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>

<div id="content">
    {% block content %}{% endblock %}
</div>

<hr>

<!-- footer -->
<div class="container">
    <div class="row">
        <div class="col-sm-12">

            <!-- Logged user info -->
            {% if user.is_authenticated %}
                <p class="text-center">
                    | Logged user: {{ user.username }}
                    | Email: {{ user.email }}
                    | <a href="{% url 'logout' %}">Sign Out</a>
                </p>
            {% endif %}
        </div>
    </div>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
</div>

</body>
</html>

blog/templates/blog/create_comment.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">

                <!-- Form - Blog Post -->
                <form action="" method="post" class="form-horizontal">

                    {% csrf_token %}

                    <div class="form-group">
                        <div class="col-sm-9">
                            <!-- Errors - body -->
                            {% if form.vote.errors %}
                                <label class="alert alert-danger">{{ form.body.errors }}</label>
                            {% endif %}

                            <!-- Form fields - body -->
                            <ul>
                            {% for choice in choices %}
                              <li>
                                <input type="radio" name="vote" value="{{choice.0}}"
                                  {% ifequal form.vote.data choice.0 %} 
                                     checked="checked"
                                  {% endifequal %}/>
                                <label for="">{{choice.1}}</label>
                              </li>
                            {% endfor %}
                            </ul>
                    <div class="form-group">
                        <div class="col-sm-9">

                            <!-- Submit button -->
                            <button type="submit" class="btn btn-primary btn-block">Save</button>

                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
{% endblock content %}

blog/templates/blog/findMissing.html
{% extends 'blog/base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="search" value="Search" />
  </form>
{% endblock %}

blog/templates/blog/helprequests.html
{% extends "blog/base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/table.css' %}"/>
<div class="caption">Requests</div>    
        <div class="starter-template">
            {% for req in rqsts %}
                <div class="row">
                    <input type="radio" name="expand">
                    <a href="{% url 'blog:request' req.pk %}"><span class="cell primary" data-label="Vehicle">{{req.body.body}}</span></a>
                    <span class="cell" data-label="Exterior">{{choices|get_item:req.status}}</span>
                    {%if req.assigned_to %}
                    <span class="cell" data-label="Interior">{{req.assigned_to.first_name}}, {{req.assigned_to.last_name}}</span>
                    {% endif %}

                    {%if not req.assigned_to %}
                    <span class="cell" data-label="Interior">Not Assigned</span>
                    {% endif %}
                    <span class="cell" data-label="Engine">{{req.pub_date}}</span>
                </div>
            {% endfor %}
        </div>
        <!-- Pagination -->
        <div class="pagination">
            {% if rqsts.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ rqsts.previous_page_number }}">previous</a>
            {% endif %}

            {% if rqsts.paginator.num_pages != 1 %}
                Page {{ rqsts.number }} of {{ rqsts.paginator.num_pages }}.
            {% endif %}

            {% if rqsts.has_next %}
                <a href="?page={{ posts.next_page_number }}">next</a>
                <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </div>

    </div>
{% endblock content %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container">

        <header class="jumbotron my-8">
        <h1 class="display-3">A Warm Welcome!</h1>
        <p class="lead">A disaster help prediction/classification system</p>
        </header>

        <div class="row">

        <div class="col-xs-12">
          {% for post in posts %}
          <div class="jumbotron my-32">
            <h4 class="card-title"><a href="{% url 'blog:post' post.pk %}">{{ post.body }}</a></h4>
              <p class="card-text">Predicted class : {{classes|get_item:post.clss}}</p>
              <a href="{% url 'blog:post_clas' post.clss %}" class="btn btn-primary">Click for more of {{classes|get_item:post.clss}}</a><br/><br/>
              </div>
            {% endfor %}
            </div>
          </div>
    </div>
{% endblock content %}

blog/templates/blog/login.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container">
        <div class="row" style="margin-top:20px">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">

                <!-- Errors messages -->
                <div class="col-sm-9">

                    {% if form.errors %}
                        <div class="alert alert-danger">Your username and password didn't match. Please try again.</div>
                    {% else %}
                        {% if next %}
                            {% if user.is_authenticated %}
                                <div class="alert alert-info">Your account doesn't have access to this page. To proceed,
                                    please login with an account that has access.
                                </div>
                            {% else %}
                                <div class="alert alert-info">Please login to see this page.</div>
                            {% endif %}
                        {% endif %}
                    {% endif %}

                </div>

                <!-- Form - Login -->
                <form method="post" action="{% url 'login' %}" class="form-horizontal">

                    {% csrf_token %}

                    <div class="form-group">
                        <div class="col-sm-9">

                            <!-- Form field - username -->
                            <input type="text"
                                   placeholder="Username"
                                   class="form-control"
                                   name="username">

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-9">

                            <!-- Form field - password -->
                            <input type="password"
                                   placeholder="Password"
                                   class="form-control"
                                   name="password">

                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-9">

                            <input type="submit" class="btn  btn-primary btn-block" value="Login"/>

                        </div>
                    </div>

                    <!-- Form field - next -->
                    <!-- Used to configure redirect after successful login -->
                    <input type="hidden" name="next" value="{% url 'blog:home' %}"/>

                </form>

            </div>
        </div>

    </div>
{% endblock %}

blog/templates/blog/post.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container">

        <!-- Post -->
        <div class="jumbotron">

            <!-- Post title -->
            <h1>{{ post.title }}</h1>

            <div> Created {{ post.pub_date }}
            </div>

            <!-- Post body -->
            <h3>{{ post.body }}</h3>

            <!-- Show Update and Delete button only if User is the owner of the Post -->

        </div>

        <h2>Top Voted classes </h2>

        <!-- Comments -->
        {% for key, value in votes.items %} 
            <div class="well">
                <li>{{key}} - {{value}}</li>
            </div>
        {% endfor %}

        <!-- Show Comment button only if User is authenticated -->
        {% if user.is_authenticated %}

            <!-- Comment button -->
            <a href="{% url 'blog:create_comment' post.pk %}" class="col-md-2 pull-right">
                <button type="button" class="btn btn-primary btn-block">Vote</button>
            </a>

        {% endif %}

    </div>
{% endblock content %}

blog/templates/blog/post_class.html
{% extends "blog/base.html" %}

{% block content %}
      <div class="row-center">
        <div class="col-xs-12">
          {% for post in posts %}
          <div class="jumbotron my-6">
            <h4 class="card-title" style="text-align: center;"><a href="{% url 'blog:post' post.pk %}">{{ post.body }}</a></h4>
              </div>
            {% endfor %}
            </div>
          </div>
{% endblock content %}

blog/templates/blog/request.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container">

        <!-- Post -->
        <div class="jumbotron">

            <!-- Post title -->
            <h4>{{ req.body }}</h4>

            {% if req.assigned_to %}
            <div> Assigned to {{ req.assigned_to.first_name }} {{ req.assigned_to.last_name }} 
            </div>
            {% endif %}
            <!-- Post body -->
            <h3>{{ choices|get_item:req.status }}</h3>

        </div>

        <!-- Show Comment button only if User is authenticated -->
        {% if is_volunteer %}

            <!-- Comment button -->
            <a href="{% url 'blog:resolution' request.pk %}" class="col-md-2 pull-right">
                <button type="button" class="btn btn-primary btn-block">Resolution</button>
            </a>

        {% endif %}

    </div>
{% endblock content %}

blog/templates/blog/results.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>{{result}}</h1>
{% endblock %}

blog/templates/blog/volunteer.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container">

        <h2>Would you be kind enough to help?</h2>
        <a href="{% url 'blog:accept_volunteering' post.pk %}" class="col-md-2 pull-right">
                <button type="button" class="btn btn-primary btn-block">Yes</button>
        </a>

        <a href="{% url 'blog:reject_volunteering' post.pk %}" class="col-md-2 pull-right">
                <button type="button" class="btn btn-primary btn-block">No, Sorry</button>
        </a>


    </div>
{% endblock content %}